### PR TITLE
added install scripts for RAPID prerequisites

### PR DESCRIPTION
**Pull request by snowman2**
Hi Cedric,

I figured the correct installation script should be located with each version so you know how to install each version (saves confusion). As such, I added it to the repo. If you agree, feel free to merge!

Alan

### CODE REVIEW

**Comment by c-h-david** [comment]
Hi Alan, 
Thank you for proposing the inclusion of these scripts.  I think they could together eventually be very useful to RAPID users.  However (and this has been my main concern since we initially worked on these a while back) there is significant overlap between the four scripts.  From a maintenance perspective, this would mean having to update them all every time one of the libraries is updated.  In turn, this leaves room for errors, which I'd rather avoid.  One single script might also facilitate continuous integration on multiple platforms (i.e. later getting Travis CI to also run the tests on Mac OS X).  Here is what I would propose:
- One single script called "rapid_install_prereqs.sh", located inside the main directory ("rapid/"), and that would be a combination of the current rapid_install_prereqs_(linux/mac/cygwin).sh.  You could use the "uname" function to differentiate between operating systems if necessary (perhaps with the "-s" option) although it looks like the only difference might be one of the PETSc configure options.  
- Require one command line argument in which the path to an installation directory is provided, this could be run using: "./rapid_install_prereqs.sh /home/user/installz".
- Let's check whether each of the requirements has not been installed already, before proceeding with its installation.  
- Your current scripts configure PETSc with C++, this is no longer necessary (see the current ".travis.yml" file).
- I'll probably stay away from including the "linux_hpc" version that you propose.  This is very dependent on your own HPC environment.

What do you think of these suggestions?  Would you be interested in implementing them?
Best,
Cedric

**Comment by snowman2** [comment]
Hi Cedric,

I think those are great suggestions and would be a great benefit to have. I have a lot of projects I am currently working on and so it will be some time before I get to it. But, I think it would be a worthwhile venture.

Alan

**Comment by snowman2** [comment]
Hi Cedric,

In spite of what I said earlier, I implemented your suggestions because I was curious and thought it would be useful. You should try it out.

Thanks,
Alan

**Comment by snowman2** [comment]
Looks like the test had downloading issues again. Other than that, it looks like it worked.

**Comment by c-h-david** [comment]
@snowman2: thank you for your contribution to the Routing Application for Parallel computatIon of Discharge!!!

**Comment by c-h-david** [comment]
@snowman2: I have no clue what happened with your pull request.  I did a "Squash and merge" last week before closing it, and it appears this was never actually accounted for. I then found myself unable reopen the request. So I went ahead and implemented your changes, with some reformatting and with the exception of the HPC option (as mentioned above) because it is architecture dependent.  I also added a CONTRIBUTING file in which you are now included. I'm sorry that your commits were not counted as I very much value your contribution. This added capability will definitely be helpful to all RAPID users. Thank you again!

**Comment by snowman2** [comment]
No worries. I am glad that it is in!

**Pull request closed without merging**
