### PR TITLE
Expanded CLI to allow user argument to namelist

### PR DESCRIPTION
**Pull request by KMarkert**
This PR updates the RAPID model command line interface to allow user input to a specific namelist config file for model run per conversation at #21 

Changes:
 1. Update rapid_main.F90 to read command arguments and set namelist_file variable based on user input
 2. move setting of rapid version from rapid_init.F90 to new file rapid_version.F90
 3. created new file rapid_clihelp.F90 to print help/usage information for CLI
 4. Updated tst_pub* unit tests to use new cli args

New usage:
* print rapid version info: 
 ```
$ ./rapid -v
 RAPID version: 20210423-5-gb03cb93
````
* print rapid usage info: 
```
$ ./rapid -h
usage: ./rapid [-v | -o | -nl <namelist_file>]

rapid options:

  -v,  --version  :   print version information and exit
  -h,  --help     :   print usage information and exit
  -nl, --namelist :   execute rapid routing model using specified namelist config.
                      <namelist_file> is a file that contains all needed model
                      parameters as well as model option flags, and the names and
                      locations of all input files.
````
* run rapid simulation with namelist config: `$ ./rapid -nl <namelist_file>`

### CODE REVIEW

**Comment by rileyhales** [comment]
Hey @KMarkert this pull request looks awesome! I would be really interested in seeing this get merged.

@c-h-david when you're ready I'd be interested in starting a conversation about what it would take to get this reviewed, tested, etc so it could be merged. I'm amateur at fortran but I'm happy to help however I can. The BYU/GEOGloWS crowd is interested in seeing these changes get implemented if possible.

**Comment by rileyhales** [comment]
@msouff

**Comment by KMarkert** [comment]
Hey @rileyhales! This PR is a little outdated so I think I would need to go back and update based on what the most recent version of RAPID.

Last time I spoke with @c-h-david about this, there was concern that this PR changes a lot of unnecessary things and makes breaking changes. Things that need to change based on our discussion

- [ ]  argument `--namelist` should not be position dependent to allow for other argument to be included
- [ ] by default invoking `./rapid` without the `--namelist` should look for the namelist file in the same directory as the executable (keeping backwards compatibility)
- [ ] remove version and help argument
- [ ] remove unnecessary changes to whitespace, code clean up should be another PR for another time

@c-h-david did I miss anything? Please advise on next steps. I am happy to close this PR and start from scratch to make it cleaner and put some time to see this functionality in the code.

**Comment by rileyhales** [comment]
Primarily I'm interested in keeping the path to the name list feature. That would be extremely convenient for my applications. The help and version arguments are nice but aren't features I build code around so I wouldn't object to those being left out or changing.

My application that would benefit from this is targeting June for the finish. Kel- I can start a fork in the BYU-Hydroinformatics organization and try to help clean these things up if that would help. I know Cedric is traveling so it might take some time but after we hear from him I can help make the changes to move this along.

**Comment by c-h-david** [comment]
Hi @rileyhales and @KMarkert,
Thanks for reviving this thread. I started writing a long message with suggestions and checking all of the pull request code at the same time, and realized that it may be counterproductive for to ask for the features I had in mind. So I went ahead and implemented a version that was heavily inspired by @KMarkert's PR. I added @KMarkert in the [CONTRIBUTING](https://github.com/c-h-david/rapid/blob/master/CONTRIBUTING) file as an acknowledgment of the heavy lifting! The code hasn't yet passed all of its GitHub Actions because Ubuntu 18.04 is now deprecated. Use carefully for now, and let me know if this works for you?
Closing the request for now, with a HUGE THANK YOU to @KMarkert.

**Pull request closed without merging**
